services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${HOST_DATASET_PATH}"
        target: /data
        bind:
          propagation: rshared
      - ..:/piml-in-metal-am
    environment:
      - HOST_DATASET_PATH=/data
