version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Set the UID/GID arguments to match your host user
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      # Use delegated mode for better performance
      - ..:/workspace:delegated
      - ${DATASET_ROOT:-../data}:/data:delegated
      - "${EXTERNAL_DRIVE_PATH:-/tmp}:/external/l-pbf-dataset:ro"
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - PYTHONPATH=/workspace
      - DATASET_ROOT=/data
      - EXTERNAL_DRIVE_PATH=/external/l-pbf-dataset
      - DISPLAY=${DISPLAY}
    user: vscode
    command: sleep infinity