services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ${HOST_DATASET_PATH:-/dev/null}:/data:ro
      - ..:/piml-in-metal-am
    environment:
      - DATASET_ROOT=${HOST_DATASET_PATH:+/data}
